on:
  pull_request:
  push:

jobs:
  check-package-mismatches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check mismatched dependencies in workspace
        run: npx --yes syncpack check-mismatches
